### ISSUE TITLE
nmcli nm permissions command missing from the NM Command list

### ISSUE THREAD

**Issue by cjds** [ZachGoldberg/python-nmcli#2]
Attempting the command causes this error:

         nmcli.nm.permissions()
         Traceback (most recent call last):
         File "<stdin>", line 1, in <module>
         AttributeError: 'NMCommand' object has no attribute 'permissions'

Output of the command when run from the command line:

> PERMISSION                                                VALUE     
org.freedesktop.NetworkManager.enable-disable-network     yes       
org.freedesktop.NetworkManager.enable-disable-wifi        yes       
org.freedesktop.NetworkManager.enable-disable-wwan        yes       
org.freedesktop.NetworkManager.enable-disable-wimax       yes       
org.freedesktop.NetworkManager.sleep-wake                 no        
org.freedesktop.NetworkManager.network-control            yes

**Comment by ZachGoldberg** [comment]
@cjds Do you have patches already for this?   If not, I don't have time today but might be able to dive in this weekend and fix them for fun

**Comment by cjds** [comment]
@ZachGoldberg  Working on them. I should be able to get it done this weekend :-) . I was just listing them out as I found them while patching them, to make sure that I was covering anything I found

**Comment by ZachGoldberg** [comment]
@cjds wonderful ;)  Let me know if I can help, happy to review PRs etc.  God speed!
